[package]
name = "tankerkoenig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.23"
strum_macros = "0.23"
reqwest = {version = "0.11.7", features = ["json"]}
thiserror = "1.0.30"
serde = {version = "1.0.131", features = ["derive"]}
serde_json = "1.0.72"
