---
name: Cargo Publish
on:
  workflow_call:
    inputs:
      tag_name:
        type: string
        required: true
    secrets:
      TOKEN:
        required: true

jobs:
  publish_crate:
    name: Publish crate ${{ inputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name }}
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.TOKEN }}
