---
name: Cargo Publish
on:
  workflow_call:
    inputs:
      tag_name:
        type: string
        required: true
    secrets:
      TOKEN:
        required: true

jobs:
  publish_crate:
    name: Publish crate ${{ inputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name }}
      - name: Setup Cache for Rust
        uses: Swatinem/rust-cache@v2
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.TOKEN }}
