---
name: Report Coverage
on:
  workflow_call:
  workflow_dispatch:

jobs:
  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Cache for Rust
        uses: Swatinem/rust-cache@v2
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install Tarpaulin Tool
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin
      - name: Analyze Coverage
        run: cargo tarpaulin -o lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
