---
name: PR Analysis
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      build_test: false

  coverage:
    name: Coverage Report
    needs:
      - test
    uses: ./.github/workflows/coverage.yml
    secrets: inherit
