---
name: Test
on:
  workflow_call:
    inputs:
      build_test:
        description: "Should the build test be executed?"
        default: true
        required: false
        type: boolean

env:
  RUST_BACKTRACE: full
  RUSTUP_MAX_RETRIES: 100
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 100
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust_version:
          - stable
          - beta
          - nightly
          - "1.70.0" # MSRV
    steps:
      - uses: actions/checkout@v4
      - name: Setup Cache for Rust
        uses: Swatinem/rust-cache@v2
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
          components: clippy
      - name: Run clippy
        run: cargo clippy

  format:
    name: Format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version:
          - stable
          - beta
          - nightly
          - "1.70.0" # MSRV
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
          components: rustfmt
      - name: Run format
        run: cargo fmt --check -v

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version:
          - stable
          - beta
          - nightly
          - "1.70.0" # MSRV
    steps:
      - uses: actions/checkout@v4
      - name: Setup Cache for Rust
        uses: Swatinem/rust-cache@v2
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Test
        run: cargo test

  build_test:
    name: Build Test
    if: inputs.build_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version:
          - stable
          - beta
          - nightly
          - "1.70.0" # MSRV
    steps:
      - uses: actions/checkout@v4
      - name: Setup Cache for Rust
        uses: Swatinem/rust-cache@v2
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Build
        run: cargo build
